default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test: &test
  <<: *default
  database: serber_test

development: &test
  <<: *default
  database: serber_dev
